name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [ '16-ea']
      fail-fast: false
    name: ${{ matrix.os }} JDK ${{ matrix.java }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Save default Java Home
      run: echo "JDK_DEF=$(echo $JAVA_HOME)" >> $GITHUB_ENV
    - name: Set up JDK
      id: setupjdk
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Echo JAVA_HOME
      run: echo $JAVA_HOME
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build with Gradle
      run: ./gradlew -Dorg.gradle.java.home="${JDK_DEF}" -Porg.gradle.java.installations.paths="${{ steps.setupjdk.outputs.path }}" buildJPackages --scan --info --stacktrace
    - name: Upload DMG as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: supernautfx-hello-jdk${{ matrix.java }}-${{ matrix.os }}-dmg
        path: supernautfx-hello/build/jpackage/*.dmg
        if-no-files-found: ignore
    - name: Upload EXE as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: supernautfx-hello-jdk${{ matrix.java }}-${{ matrix.os }}-exe
        path: supernautfx-hello/build/jpackage/*.exe
        if-no-files-found: ignore
    - name: Upload DEB as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: supernautfx-hello-jdk${{ matrix.java }}-${{ matrix.os }}-deb
        path: supernautfx-hello/build/jpackage/*.deb
        if-no-files-found: ignore
    - name: Upload RPM as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: supernautfx-hello-jdk${{ matrix.java }}-${{ matrix.os }}-rpm
        path: supernautfx-hello/build/jpackage/*.rpm
        if-no-files-found: ignore
